"""Statement domain models: Statement."""

from typing import ClassVar

from sqlalchemy import (
    Column,
    Computed,
    ForeignKey,
    Index,
    String,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from .base import (
    Base,
    TimestampMixin,
    UpsertMixin,
)


class Statement(Base, TimestampMixin, UpsertMixin):
    """Cached Wikidata REST statement document for a politician.

    The document is stored canonically in its Wikibase REST API shape; the
    derived columns (wikidata_statement_id, property_id, entity_id) are
    generated by PostgreSQL from the document.
    """

    __tablename__ = "statements"
    __table_args__ = (
        UniqueConstraint(
            "wikidata_statement_id", name="uq_statements_wikidata_statement_id"
        ),
        Index("idx_statements_politician_property", "politician_id", "property_id"),
        Index(
            "idx_statements_politician_property_entity",
            "politician_id",
            "property_id",
            "entity_id",
        ),
        Index("idx_statements_updated_at", "updated_at"),
    )

    # UpsertMixin configuration
    _upsert_conflict_columns: ClassVar[list[str]] = ["wikidata_statement_id"]
    _upsert_update_columns: ClassVar[list[str]] = ["document"]

    id = Column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    politician_id = Column(
        UUID(as_uuid=True),
        ForeignKey("politicians.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    document = Column(JSONB, nullable=False)  # Canonical REST statement document
    wikidata_statement_id = Column(
        String,
        Computed("document ->> 'id'"),
        nullable=False,
    )
    property_id = Column(
        String,
        Computed("document #>> '{property,id}'"),
        nullable=False,
    )
    entity_id = Column(
        String,
        Computed(
            "CASE WHEN document #>> '{property,id}' IN ('P19','P27','P39') "
            "THEN document #>> '{value,content}' END"
        ),
        ForeignKey("wikidata_entities.wikidata_id", ondelete="CASCADE"),
        nullable=True,
    )

    # Relationships
    politician = relationship("Politician", back_populates="statements")


def active_citizenship_conditions(citizenship, *, politician_id=None, countries=None):
    """Return common live-citizenship predicates for a Statement table or alias."""
    conditions = []
    if politician_id is not None:
        conditions.append(citizenship.politician_id == politician_id)
    conditions.append(citizenship.property_id == "P27")
    if countries:
        conditions.append(citizenship.entity_id.in_(countries))
    return conditions
