"""Add indexes to user_id and preference_type in preferences table

Revision ID: 07231531a553
Revises: b5655af2721c
Create Date: 2025-09-27 00:36:16.743045

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "07231531a553"
down_revision: Union[str, None] = "b5655af2721c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_preferences_preference_type"),
        "preferences",
        ["preference_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_preferences_user_id"), "preferences", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_preferences_user_id"), table_name="preferences")
    op.drop_index(op.f("ix_preferences_preference_type"), table_name="preferences")
    # ### end Alembic commands ###
