"""Add qualifiers_json column to holds_position and born_at tables

Revision ID: 084925595654
Revises: 4cde531b1561
Create Date: 2025-09-23 13:34:56.922741

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "084925595654"
down_revision: Union[str, None] = "4cde531b1561"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "born_at",
        sa.Column(
            "qualifiers_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "holds_position",
        sa.Column(
            "qualifiers_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("holds_position", "qualifiers_json")
    op.drop_column("born_at", "qualifiers_json")
    # ### end Alembic commands ###
