"""refactor country to reference wikidata_entity drop name column

Revision ID: 146440e7d68e
Revises: d5ea56ee13ac
Create Date: 2025-09-10 16:40:45.491149

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "146440e7d68e"
down_revision: Union[str, None] = "d5ea56ee13ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "countries", "wikidata_entities", ["wikidata_id"], ["wikidata_id"]
    )
    op.drop_column("countries", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "countries",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "countries", type_="foreignkey")
    # ### end Alembic commands ###
