"""Add indexes for deleted_at and politician_id

Revision ID: 16e6e629a64e
Revises: 07231531a553
Create Date: 2025-09-27 23:53:41.992229

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "16e6e629a64e"
down_revision: Union[str, None] = "07231531a553"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_properties_deleted_at"), "properties", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_properties_politician_id"),
        "properties",
        ["politician_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wikidata_entities_deleted_at"),
        "wikidata_entities",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wikidata_relations_deleted_at"),
        "wikidata_relations",
        ["deleted_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_wikidata_relations_deleted_at"), table_name="wikidata_relations"
    )
    op.drop_index(
        op.f("ix_wikidata_entities_deleted_at"), table_name="wikidata_entities"
    )
    op.drop_index(op.f("ix_properties_politician_id"), table_name="properties")
    op.drop_index(op.f("ix_properties_deleted_at"), table_name="properties")
    # ### end Alembic commands ###
