"""add_cascade_to_has_citizenship_country_fkey

Revision ID: 172f4b4de36f
Revises: 97de81eb2339
Create Date: 2025-09-19 16:02:10.487157

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "172f4b4de36f"
down_revision: Union[str, None] = "97de81eb2339"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop the composite unique constraint first to improve performance
    op.drop_constraint("uq_politician_country", "has_citizenship", type_="unique")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("has_citizenship_country_id_fkey"), "has_citizenship", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "has_citizenship",
        "countries",
        ["country_id"],
        ["wikidata_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "has_citizenship", type_="foreignkey")
    op.create_foreign_key(
        op.f("has_citizenship_country_id_fkey"),
        "has_citizenship",
        "countries",
        ["country_id"],
        ["wikidata_id"],
    )
    # ### end Alembic commands ###
