"""drop_revision_column_from_archived_pages

Revision ID: 1bc6a146df39
Revises: cadc912d1eba
Create Date: 2025-11-24 14:27:03.213380

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1bc6a146df39"
down_revision: Union[str, None] = "cadc912d1eba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("archived_pages", "revision")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archived_pages",
        sa.Column("revision", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
