"""Add partial unique indexes for Wikidata relationships

Revision ID: 2cac5a7c8d62
Revises: 5aef915e0ed0
Create Date: 2025-08-29 15:44:56.417552

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2cac5a7c8d62"
down_revision: Union[str, None] = "5aef915e0ed0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_born_at_wikidata_only",
        "born_at",
        ["politician_id", "location_id"],
        unique=True,
        postgresql_where=sa.text("archived_page_id IS NULL"),
    )
    op.create_unique_constraint(
        "uq_politician_country", "has_citizenship", ["politician_id", "country_id"]
    )
    op.create_index(
        "uq_holds_position_wikidata_only",
        "holds_position",
        ["politician_id", "position_id"],
        unique=True,
        postgresql_where=sa.text("archived_page_id IS NULL"),
    )
    op.drop_constraint(
        op.f("uq_properties_politician_type"), "properties", type_="unique"
    )
    op.create_index(
        "uq_property_wikidata_only",
        "properties",
        ["politician_id", "type"],
        unique=True,
        postgresql_where=sa.text("archived_page_id IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_property_wikidata_only",
        table_name="properties",
        postgresql_where=sa.text("archived_page_id IS NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_properties_politician_type"),
        "properties",
        ["politician_id", "type"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(
        "uq_holds_position_wikidata_only",
        table_name="holds_position",
        postgresql_where=sa.text("archived_page_id IS NULL"),
    )
    op.drop_constraint("uq_politician_country", "has_citizenship", type_="unique")
    op.drop_index(
        "uq_born_at_wikidata_only",
        table_name="born_at",
        postgresql_where=sa.text("archived_page_id IS NULL"),
    )
    # ### end Alembic commands ###
