"""add cascade delete to tracking table fk

Revision ID: 2d84bed67490
Revises: 8acdc0c13b02
Create Date: 2025-11-27 16:10:19.277423

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2d84bed67490"
down_revision: Union[str, None] = "8acdc0c13b02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("current_import_entities_entity_id_fkey"),
        "current_import_entities",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "current_import_entities",
        "wikidata_entities",
        ["entity_id"],
        ["wikidata_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "current_import_entities", type_="foreignkey")
    op.create_foreign_key(
        op.f("current_import_entities_entity_id_fkey"),
        "current_import_entities",
        "wikidata_entities",
        ["entity_id"],
        ["wikidata_id"],
    )
    # ### end Alembic commands ###
