"""Add indexes for stats query optimization

Revision ID: 362f0d0d7ac8
Revises: 2d84bed67490
Create Date: 2025-12-12 11:48:28.234840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "362f0d0d7ac8"
down_revision: Union[str, None] = "2d84bed67490"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_evaluations_created_at", "evaluations", ["created_at"], unique=False
    )
    op.create_index(
        "idx_evaluations_property_created",
        "evaluations",
        ["property_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_properties_extracted",
        "properties",
        ["politician_id", "archived_page_id"],
        unique=False,
        postgresql_where=sa.text("archived_page_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_index(
        "idx_properties_wikidata_citizenship",
        "properties",
        ["politician_id"],
        unique=False,
        postgresql_where=sa.text(
            "type = 'CITIZENSHIP' AND statement_id IS NOT NULL AND deleted_at IS NULL"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_properties_wikidata_citizenship",
        table_name="properties",
        postgresql_where=sa.text(
            "type = 'CITIZENSHIP' AND statement_id IS NOT NULL AND deleted_at IS NULL"
        ),
    )
    op.drop_index(
        "idx_properties_extracted",
        table_name="properties",
        postgresql_where=sa.text("archived_page_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index("idx_evaluations_property_created", table_name="evaluations")
    op.drop_index("idx_evaluations_created_at", table_name="evaluations")
    # ### end Alembic commands ###
