"""Add unique constraint to properties table

Revision ID: 37f7fcd0368b
Revises: 846c5485755a
Create Date: 2025-07-17 17:00:48.359229

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "37f7fcd0368b"
down_revision: Union[str, None] = "846c5485755a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_properties_politician_type", "properties", ["politician_id", "type"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_properties_politician_type", "properties", type_="unique")
    # ### end Alembic commands ###
