"""Add foreign key from Politician.wikidata_id to WikidataEntity

Revision ID: 3b5cfba705c9
Revises: 0302be2a0730
Create Date: 2025-09-16 18:32:20.111129

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3b5cfba705c9"
down_revision: Union[str, None] = "0302be2a0730"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create missing wikidata_entities for existing politicians
    op.execute("""
        INSERT INTO wikidata_entities (wikidata_id, name, created_at, updated_at)
        SELECT DISTINCT
            p.wikidata_id,
            p.name,
            NOW(),
            NOW()
        FROM politicians p
        WHERE p.wikidata_id IS NOT NULL
        AND NOT EXISTS (
            SELECT 1 FROM wikidata_entities w
            WHERE w.wikidata_id = p.wikidata_id
        )
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "politicians", "wikidata_entities", ["wikidata_id"], ["wikidata_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "politicians", type_="foreignkey")
    # ### end Alembic commands ###
