"""Remove position_classes and location_classes junction tables

Revision ID: 3e0d33c32bb6
Revises: 4c95e5af0ef6
Create Date: 2025-09-06 20:50:51.041222

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e0d33c32bb6"
down_revision: Union[str, None] = "4c95e5af0ef6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("position_classes")
    op.drop_table("location_classes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_classes",
        sa.Column("location_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("class_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["wikidata_classes.wikidata_id"],
            name=op.f("location_classes_class_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.wikidata_id"],
            name=op.f("location_classes_location_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "location_id", "class_id", name=op.f("location_classes_pkey")
        ),
    )
    op.create_table(
        "position_classes",
        sa.Column("position_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("class_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["wikidata_classes.wikidata_id"],
            name=op.f("position_classes_class_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.wikidata_id"],
            name=op.f("position_classes_position_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "position_id", "class_id", name=op.f("position_classes_pkey")
        ),
    )
    # ### end Alembic commands ###
