"""Remove unique constraint on countries.iso_code

Revision ID: 44052556e590
Revises: c39f3d863772
Create Date: 2025-09-20 11:02:52.329948

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "44052556e590"
down_revision: Union[str, None] = "c39f3d863772"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_countries_iso_code"), table_name="countries")
    op.create_index(
        op.f("ix_countries_iso_code"), "countries", ["iso_code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_countries_iso_code"), table_name="countries")
    op.create_index(
        op.f("ix_countries_iso_code"), "countries", ["iso_code"], unique=True
    )
    # ### end Alembic commands ###
