"""Drop is_deceased column from politicians table

Revision ID: 47390e7bb18e
Revises: 4bd8515dc7c8
Create Date: 2025-07-15 19:06:37.986410

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47390e7bb18e"
down_revision: Union[str, None] = "4bd8515dc7c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Drop the is_deceased column from politicians table.

    The is_deceased status is now derived from the presence of DeathDate properties
    in the properties table, eliminating data redundancy.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("politicians", "is_deceased")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Re-add the is_deceased column to politicians table.

    Note: If downgrading, you'll need to populate the is_deceased column
    based on existing DeathDate properties in the properties table.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "politicians",
        sa.Column("is_deceased", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
