"""Remove date columns from holds_position table

Revision ID: 4b2fb2f20669
Revises: 56510affb959
Create Date: 2025-09-23 18:12:39.957698

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b2fb2f20669"
down_revision: Union[str, None] = "56510affb959"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("holds_position", "start_date")
    op.drop_column("holds_position", "start_date_precision")
    op.drop_column("holds_position", "end_date_precision")
    op.drop_column("holds_position", "end_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "holds_position",
        sa.Column("end_date", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "holds_position",
        sa.Column(
            "end_date_precision", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "holds_position",
        sa.Column(
            "start_date_precision", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "holds_position",
        sa.Column("start_date", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
