"""Add description columns to positions and locations

Revision ID: 4c95e5af0ef6
Revises: 4797852d86b9
Create Date: 2025-09-06 20:31:29.093346

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c95e5af0ef6"
down_revision: Union[str, None] = "4797852d86b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("locations", sa.Column("description", sa.String(), nullable=True))
    op.add_column("positions", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("positions", "description")
    op.drop_column("locations", "description")
    # ### end Alembic commands ###
