"""add statement_id to wikidata_relations

Revision ID: 4cde531b1561
Revises: 44052556e590
Create Date: 2025-09-23 13:12:50.891026

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4cde531b1561"
down_revision: Union[str, None] = "44052556e590"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Truncate existing relations since they lack statement_ids
    # These will be re-imported with statement_ids during the next hierarchy import
    op.execute("TRUNCATE TABLE wikidata_relations")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wikidata_relations", sa.Column("statement_id", sa.String(), nullable=False)
    )
    op.create_index(
        "uq_wikidata_relations_statement_id",
        "wikidata_relations",
        ["statement_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_wikidata_relations_statement_id", table_name="wikidata_relations")
    op.drop_column("wikidata_relations", "statement_id")
    # ### end Alembic commands ###
