"""add_wikimedia_code_to_languages

Revision ID: 4e5af7bd6700
Revises: c0a6d8624a67
Create Date: 2025-11-19 19:40:44.843051

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e5af7bd6700"
down_revision: Union[str, None] = "c0a6d8624a67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archived_pages", sa.Column("wikimedia_code", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_archived_pages_wikimedia_code"),
        "archived_pages",
        ["wikimedia_code"],
        unique=False,
    )
    op.add_column("languages", sa.Column("wikimedia_code", sa.String(), nullable=True))
    op.drop_index(op.f("idx_languages_iso1_code"), table_name="languages")
    op.drop_index(op.f("idx_languages_iso3_code"), table_name="languages")
    op.create_index(
        op.f("ix_languages_wikimedia_code"),
        "languages",
        ["wikimedia_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_languages_wikimedia_code"), table_name="languages")
    op.create_index(
        op.f("idx_languages_iso3_code"), "languages", ["iso3_code"], unique=False
    )
    op.create_index(
        op.f("idx_languages_iso1_code"), "languages", ["iso1_code"], unique=False
    )
    op.drop_column("languages", "wikimedia_code")
    op.drop_index(op.f("ix_archived_pages_wikimedia_code"), table_name="archived_pages")
    op.drop_column("archived_pages", "wikimedia_code")
    # ### end Alembic commands ###
