"""Replace iso_code with iso1_code and iso3_code using LanguageCodeMixin

Revision ID: 53a44de8d7ff
Revises: ca1f55abed5b
Create Date: 2025-09-25 15:15:35.515724

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "53a44de8d7ff"
down_revision: Union[str, None] = "ca1f55abed5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Truncate archived_pages table since existing records have no iso_code
    # and we need iso1_code/iso3_code for the new schema
    op.execute("TRUNCATE TABLE archived_pages CASCADE")

    op.add_column("archived_pages", sa.Column("iso1_code", sa.String(), nullable=True))
    op.add_column("archived_pages", sa.Column("iso3_code", sa.String(), nullable=True))
    op.drop_index(op.f("ix_archived_pages_iso_code"), table_name="archived_pages")
    op.create_index(
        op.f("ix_archived_pages_iso1_code"),
        "archived_pages",
        ["iso1_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_archived_pages_iso3_code"),
        "archived_pages",
        ["iso3_code"],
        unique=False,
    )
    op.drop_column("archived_pages", "iso_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archived_pages",
        sa.Column("iso_code", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_archived_pages_iso3_code"), table_name="archived_pages")
    op.drop_index(op.f("ix_archived_pages_iso1_code"), table_name="archived_pages")
    op.create_index(
        op.f("ix_archived_pages_iso_code"), "archived_pages", ["iso_code"], unique=False
    )
    op.drop_column("archived_pages", "iso3_code")
    op.drop_column("archived_pages", "iso1_code")
    # ### end Alembic commands ###
