"""Add performance indexes for properties table

Revision ID: 5508470c1e0d
Revises: 96ffbd77b75c
Create Date: 2025-11-23 12:16:51.270017

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5508470c1e0d"
down_revision: Union[str, None] = "96ffbd77b75c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_properties_type_entity",
        "properties",
        ["type", "entity_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_properties_type"), "properties", ["type"], unique=False)

    # Create composite index for efficient language queries
    op.create_index(
        "idx_wikidata_relations_child_relation",
        "wikidata_relations",
        ["child_entity_id", "relation_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_wikidata_relations_child_relation", table_name="wikidata_relations"
    )
    op.drop_index(op.f("ix_properties_type"), table_name="properties")
    op.drop_index(
        "idx_properties_type_entity",
        table_name="properties",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###
