"""Add statement_id, qualifiers_json, references_json to properties table via StatementMixin

Revision ID: 56510affb959
Revises: 6eab5cce7d23
Create Date: 2025-09-23 17:13:50.451384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "56510affb959"
down_revision: Union[str, None] = "6eab5cce7d23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "properties",
        sa.Column(
            "qualifiers_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "properties",
        sa.Column(
            "references_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("properties", "references_json")
    op.drop_column("properties", "qualifiers_json")
    # ### end Alembic commands ###
