"""add_user_id_to_archived_pages

Revision ID: 5e22c7045b45
Revises: b351d1ca5357
Create Date: 2026-02-17 19:48:02.094077

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e22c7045b45"
down_revision: str | None = "b351d1ca5357"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("archived_pages", sa.Column("user_id", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_archived_pages_user_id"), "archived_pages", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_archived_pages_user_id"), table_name="archived_pages")
    op.drop_column("archived_pages", "user_id")
    # ### end Alembic commands ###
