"""Add statement_id to has_citizenship table

Revision ID: 6238599a40c3
Revises: a025b8f896dc
Create Date: 2025-09-19 14:27:59.966237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6238599a40c3"
down_revision: Union[str, None] = "a025b8f896dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "has_citizenship", sa.Column("statement_id", sa.String(), nullable=True)
    )
    op.create_index(
        "uq_has_citizenship_statement_id",
        "has_citizenship",
        ["statement_id"],
        unique=True,
        postgresql_where=sa.text("statement_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_has_citizenship_statement_id",
        table_name="has_citizenship",
        postgresql_where=sa.text("statement_id IS NOT NULL"),
    )
    op.drop_column("has_citizenship", "statement_id")
    # ### end Alembic commands ###
