"""add_hierarchy_tables_with_uuid_primary_keys

Revision ID: 6345bbdce2e7
Revises: 791c7593cd8a
Create Date: 2025-08-22 10:54:26.861953

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6345bbdce2e7"
down_revision: Union[str, None] = "791c7593cd8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikidata_classes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("wikidata_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wikidata_classes_wikidata_id"),
        "wikidata_classes",
        ["wikidata_id"],
        unique=True,
    )
    op.create_table(
        "subclass_relations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parent_class_id", sa.UUID(), nullable=False),
        sa.Column("child_class_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_class_id"],
            ["wikidata_classes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_class_id"],
            ["wikidata_classes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parent_class_id", "child_class_id", name="uq_subclass_parent_child"
        ),
    )
    op.create_index(
        op.f("ix_subclass_relations_child_class_id"),
        "subclass_relations",
        ["child_class_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subclass_relations_parent_class_id"),
        "subclass_relations",
        ["parent_class_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_subclass_relations_parent_class_id"), table_name="subclass_relations"
    )
    op.drop_index(
        op.f("ix_subclass_relations_child_class_id"), table_name="subclass_relations"
    )
    op.drop_table("subclass_relations")
    op.drop_index(
        op.f("ix_wikidata_classes_wikidata_id"), table_name="wikidata_classes"
    )
    op.drop_table("wikidata_classes")
    # ### end Alembic commands ###
