"""Add updated_at indexes for garbage collection performance

Revision ID: 644e26e83904
Revises: 16e6e629a64e
Create Date: 2025-09-28 00:03:41.753577

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "644e26e83904"
down_revision: Union[str, None] = "16e6e629a64e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_properties_updated_at", "properties", ["updated_at"], unique=False
    )
    op.create_index(
        "idx_wikidata_entities_updated_at",
        "wikidata_entities",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        "idx_wikidata_relations_updated_at",
        "wikidata_relations",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_wikidata_relations_updated_at", table_name="wikidata_relations")
    op.drop_index("idx_wikidata_entities_updated_at", table_name="wikidata_entities")
    op.drop_index("idx_properties_updated_at", table_name="properties")
    # ### end Alembic commands ###
