"""replace_iso_code_with_wikipedia_project_id_in_wikipedia_links

Revision ID: 6467179d6d1d
Revises: ee79ae61a692
Create Date: 2025-11-20 20:18:13.760902

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6467179d6d1d"
down_revision: Union[str, None] = "ee79ae61a692"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add wikipedia_project_id column as nullable
    op.add_column(
        "wikipedia_links", sa.Column("wikipedia_project_id", sa.String(), nullable=True)
    )

    # Step 2: Populate wikipedia_project_id by extracting language code from URL
    # Match URLs like https://en.wikipedia.org/wiki/... to wikipedia projects
    op.execute("""
        UPDATE wikipedia_links wl
        SET wikipedia_project_id = wp.wikidata_id
        FROM wikipedia_projects wp
        WHERE wp.official_website LIKE 'https://' || wl.iso_code || '.wikipedia.org%'
    """)

    # Step 3: Delete wikipedia_links that couldn't be matched to a project
    op.execute("""
        DELETE FROM wikipedia_links
        WHERE wikipedia_project_id IS NULL
    """)

    # Step 4: Make wikipedia_project_id non-nullable
    op.alter_column("wikipedia_links", "wikipedia_project_id", nullable=False)

    # Step 5: Drop old indexes and create new ones
    op.drop_index(
        op.f("idx_wikipedia_links_politician_iso_code"), table_name="wikipedia_links"
    )
    op.drop_index(op.f("ix_wikipedia_links_iso_code"), table_name="wikipedia_links")
    op.create_index(
        "idx_wikipedia_links_politician_project",
        "wikipedia_links",
        ["politician_id", "wikipedia_project_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_wikipedia_links_wikipedia_project_id"),
        "wikipedia_links",
        ["wikipedia_project_id"],
        unique=False,
    )

    # Step 6: Add foreign key constraint
    op.create_foreign_key(
        "wikipedia_links_wikipedia_project_id_fkey",
        "wikipedia_links",
        "wikipedia_projects",
        ["wikipedia_project_id"],
        ["wikidata_id"],
        ondelete="CASCADE",
    )

    # Step 7: Drop iso_code column
    op.drop_column("wikipedia_links", "iso_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Note: This downgrade will lose data as we cannot reliably reconstruct iso_code from wikipedia_project_id
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wikipedia_links",
        sa.Column("iso_code", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        "wikipedia_links_wikipedia_project_id_fkey",
        "wikipedia_links",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_wikipedia_links_wikipedia_project_id"), table_name="wikipedia_links"
    )
    op.drop_index(
        "idx_wikipedia_links_politician_project", table_name="wikipedia_links"
    )
    op.create_index(
        op.f("ix_wikipedia_links_iso_code"),
        "wikipedia_links",
        ["iso_code"],
        unique=False,
    )
    op.create_index(
        op.f("idx_wikipedia_links_politician_iso_code"),
        "wikipedia_links",
        ["politician_id", "iso_code"],
        unique=True,
    )
    op.drop_column("wikipedia_links", "wikipedia_project_id")
    # ### end Alembic commands ###
