"""add wikipedia_project_id to archived_pages

Revision ID: 6528df629848
Revises: 5508470c1e0d
Create Date: 2025-11-23 15:27:25.325964

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6528df629848"
down_revision: Union[str, None] = "5508470c1e0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archived_pages", sa.Column("wikipedia_project_id", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_archived_pages_wikipedia_project_id"),
        "archived_pages",
        ["wikipedia_project_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "archived_pages",
        "wikipedia_projects",
        ["wikipedia_project_id"],
        ["wikidata_id"],
        ondelete="SET NULL",
    )

    # Migrate existing data: link archived pages to Wikipedia projects via URL matching
    # Match archived page URL to wikipedia_link URL, then get the project ID
    op.execute("""
        UPDATE archived_pages ap
        SET wikipedia_project_id = wl.wikipedia_project_id
        FROM wikipedia_links wl
        WHERE ap.url = wl.url
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "archived_pages", type_="foreignkey")
    op.drop_index(
        op.f("ix_archived_pages_wikipedia_project_id"), table_name="archived_pages"
    )
    op.drop_column("archived_pages", "wikipedia_project_id")
    # ### end Alembic commands ###
