"""drop position and location country association tables

Revision ID: 674f632a8606
Revises: 228051ec07ac
Create Date: 2025-07-08 17:04:40.405519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674f632a8606'
down_revision: Union[str, None] = '228051ec07ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_country')
    op.drop_table('location_country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_country',
    sa.Column('location_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('location_country_country_id_fkey')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('location_country_location_id_fkey')),
    sa.PrimaryKeyConstraint('location_id', 'country_id', name=op.f('location_country_pkey'))
    )
    op.create_table('position_country',
    sa.Column('position_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('position_country_country_id_fkey')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('position_country_position_id_fkey')),
    sa.PrimaryKeyConstraint('position_id', 'country_id', name=op.f('position_country_pkey'))
    )
    # ### end Alembic commands ###
