"""Add unique index on wikipedia_links politician_id and language_code

Revision ID: 6df466099161
Revises: bb1c034b9515
Create Date: 2025-09-03 14:03:31.098735

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6df466099161"
down_revision: Union[str, None] = "bb1c034b9515"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_wikipedia_links_politician_language",
        "wikipedia_links",
        ["politician_id", "language_code"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_wikipedia_links_politician_language", table_name="wikipedia_links"
    )
    # ### end Alembic commands ###
