"""Add references_json to HoldsPosition and BornAt models

Revision ID: 6eab5cce7d23
Revises: e61ba5f53b3f
Create Date: 2025-09-23 16:08:48.233362

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6eab5cce7d23"
down_revision: Union[str, None] = "e61ba5f53b3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "born_at",
        sa.Column(
            "references_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "holds_position",
        sa.Column(
            "references_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("holds_position", "references_json")
    op.drop_column("born_at", "references_json")
    # ### end Alembic commands ###
