"""drop preferences table and enum

Revision ID: 741004a3d33e
Revises: 7945b3275928
Create Date: 2025-11-24 18:57:30.366057

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "741004a3d33e"
down_revision: Union[str, None] = "7945b3275928"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_preferences_preference_type"), table_name="preferences")
    op.drop_index(op.f("ix_preferences_user_id"), table_name="preferences")
    op.drop_index(op.f("uq_preferences_user_type_entity"), table_name="preferences")
    op.drop_table("preferences")
    # ### end Alembic commands ###

    # Drop the PreferenceType enum (not auto-detected by Alembic)
    op.execute("DROP TYPE IF EXISTS preferencetype")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preferences",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "preference_type",
            postgresql.ENUM("LANGUAGE", "COUNTRY", name="preferencetype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("entity_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["wikidata_entities.wikidata_id"],
            name=op.f("preferences_entity_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("preferences_pkey")),
    )
    op.create_index(
        op.f("uq_preferences_user_type_entity"),
        "preferences",
        ["user_id", "preference_type", "entity_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_preferences_user_id"), "preferences", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_preferences_preference_type"),
        "preferences",
        ["preference_type"],
        unique=False,
    )
    # ### end Alembic commands ###
