"""add status to archived_pages

Revision ID: 7e62c18f910b
Revises: da4eb3c240eb
Create Date: 2026-03-13 11:38:13.935414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7e62c18f910b"
down_revision: Union[str, None] = "da4eb3c240eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    archivedpagestatus = sa.Enum(
        "PENDING", "PROCESSING", "DONE", name="archivedpagestatus"
    )
    archivedpagestatus.create(op.get_bind())
    op.add_column(
        "archived_pages",
        sa.Column(
            "status", archivedpagestatus, server_default="PENDING", nullable=False
        ),
    )
    op.add_column("archived_pages", sa.Column("error", sa.String(), nullable=True))
    # Backfill existing rows to DONE (they are already fully processed)
    op.execute("UPDATE archived_pages SET status = 'DONE'")
    op.alter_column(
        "archived_pages", "content_hash", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "archived_pages",
        "fetch_timestamp",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "archived_pages",
        "fetch_timestamp",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "archived_pages", "content_hash", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("archived_pages", "error")
    op.drop_column("archived_pages", "status")
    sa.Enum(name="archivedpagestatus").drop(op.get_bind())
    # ### end Alembic commands ###
