"""Add description field to WikidataEntity

Revision ID: 7ea712ad912c
Revises: 705dddab0368
Create Date: 2025-09-24 19:00:54.290170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ea712ad912c"
down_revision: Union[str, None] = "705dddab0368"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wikidata_entities", sa.Column("description", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wikidata_entities", "description")
    # ### end Alembic commands ###
