"""remove_language_code_from_wikipedia_projects

Revision ID: 7f45faa1f0df
Revises: f790105d9d6d
Create Date: 2025-11-17 13:33:38.769304

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f45faa1f0df"
down_revision: Union[str, None] = "f790105d9d6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_wikipedia_projects_language_code"), table_name="wikipedia_projects"
    )
    op.drop_index(
        op.f("ix_wikipedia_projects_language_code"), table_name="wikipedia_projects"
    )
    op.drop_column("wikipedia_projects", "language_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wikipedia_projects",
        sa.Column("language_code", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f("ix_wikipedia_projects_language_code"),
        "wikipedia_projects",
        ["language_code"],
        unique=False,
    )
    op.create_index(
        op.f("idx_wikipedia_projects_language_code"),
        "wikipedia_projects",
        ["language_code"],
        unique=True,
    )
    # ### end Alembic commands ###
