"""add_cascade_delete_to_wikidata_labels_and_relations

Revision ID: 858e6436164d
Revises: 99eed1071d45
Create Date: 2025-11-05 16:06:31.992131

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "858e6436164d"
down_revision: Union[str, None] = "99eed1071d45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("wikidata_entity_labels_entity_id_fkey"),
        "wikidata_entity_labels",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "wikidata_entity_labels",
        "wikidata_entities",
        ["entity_id"],
        ["wikidata_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("wikidata_relations_parent_entity_id_fkey"),
        "wikidata_relations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("wikidata_relations_child_entity_id_fkey"),
        "wikidata_relations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "wikidata_relations",
        "wikidata_entities",
        ["parent_entity_id"],
        ["wikidata_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "wikidata_relations",
        "wikidata_entities",
        ["child_entity_id"],
        ["wikidata_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "wikidata_relations", type_="foreignkey")
    op.drop_constraint(None, "wikidata_relations", type_="foreignkey")
    op.create_foreign_key(
        op.f("wikidata_relations_child_entity_id_fkey"),
        "wikidata_relations",
        "wikidata_entities",
        ["child_entity_id"],
        ["wikidata_id"],
    )
    op.create_foreign_key(
        op.f("wikidata_relations_parent_entity_id_fkey"),
        "wikidata_relations",
        "wikidata_entities",
        ["parent_entity_id"],
        ["wikidata_id"],
    )
    op.drop_constraint(None, "wikidata_entity_labels", type_="foreignkey")
    op.create_foreign_key(
        op.f("wikidata_entity_labels_entity_id_fkey"),
        "wikidata_entity_labels",
        "wikidata_entities",
        ["entity_id"],
        ["wikidata_id"],
    )
    # ### end Alembic commands ###
