"""Add ISO 639-3 support to languages: rename iso_code to iso1_code, add iso3_code

Revision ID: 8a2b32cf5d4a
Revises: 4d8b5e4e4420
Create Date: 2025-09-24 20:52:01.933421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a2b32cf5d4a"
down_revision: Union[str, None] = "4d8b5e4e4420"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new columns
    op.add_column("languages", sa.Column("iso1_code", sa.String(), nullable=True))
    op.add_column("languages", sa.Column("iso3_code", sa.String(), nullable=True))

    # Migrate existing data: copy iso_code to iso1_code
    op.execute("UPDATE languages SET iso1_code = iso_code WHERE iso_code IS NOT NULL")

    # Drop old index and create new ones
    op.drop_index(op.f("ix_languages_iso_code"), table_name="languages")
    op.create_index("idx_languages_iso1_code", "languages", ["iso1_code"], unique=False)
    op.create_index("idx_languages_iso3_code", "languages", ["iso3_code"], unique=False)
    op.create_index(
        op.f("ix_languages_iso1_code"), "languages", ["iso1_code"], unique=False
    )
    op.create_index(
        op.f("ix_languages_iso3_code"), "languages", ["iso3_code"], unique=False
    )

    # Drop the old column
    op.drop_column("languages", "iso_code")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "languages",
        sa.Column("iso_code", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_languages_iso3_code"), table_name="languages")
    op.drop_index(op.f("ix_languages_iso1_code"), table_name="languages")
    op.drop_index("idx_languages_iso3_code", table_name="languages")
    op.drop_index("idx_languages_iso1_code", table_name="languages")
    op.create_index(
        op.f("ix_languages_iso_code"), "languages", ["iso_code"], unique=False
    )
    op.drop_column("languages", "iso3_code")
    op.drop_column("languages", "iso1_code")
    # ### end Alembic commands ###
