"""move labels from locations to wikidata_entities

Revision ID: 8a5582ba44f4
Revises: 9fdd804f8be4
Create Date: 2025-10-09 10:49:11.280389

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8a5582ba44f4"
down_revision: Union[str, None] = "9fdd804f8be4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "labels")
    op.add_column(
        "wikidata_entities", sa.Column("labels", sa.ARRAY(sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wikidata_entities", "labels")
    op.add_column(
        "locations",
        sa.Column(
            "labels", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
