"""add index on property_references archived_page_id

Revision ID: 8dcb99038884
Revises: e3debe9d17c5
Create Date: 2026-02-26 12:45:04.618489

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8dcb99038884"
down_revision: Union[str, None] = "e3debe9d17c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_property_references_archived_page_id",
        "property_references",
        ["archived_page_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_property_references_archived_page_id", table_name="property_references"
    )
    # ### end Alembic commands ###
