"""add_wikipedia_project_entity

Revision ID: 936f6249b794
Revises: 0ab17a215d6e
Create Date: 2025-11-16 14:13:10.177722

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "936f6249b794"
down_revision: Union[str, None] = "0ab17a215d6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikipedia_projects",
        sa.Column("language_code", sa.String(), nullable=False),
        sa.Column("language_id", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("wikidata_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"], ["languages.wikidata_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["wikidata_id"],
            ["wikidata_entities.wikidata_id"],
        ),
        sa.PrimaryKeyConstraint("wikidata_id"),
    )
    op.create_index(
        "idx_wikipedia_projects_language_code",
        "wikipedia_projects",
        ["language_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_wikipedia_projects_language_code"),
        "wikipedia_projects",
        ["language_code"],
        unique=False,
    )
    op.drop_index(op.f("idx_properties_entity_id"), table_name="properties")
    op.create_index(
        op.f("ix_properties_entity_id"), "properties", ["entity_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_properties_entity_id"), table_name="properties")
    op.create_index(
        op.f("idx_properties_entity_id"), "properties", ["entity_id"], unique=False
    )
    op.drop_index(
        op.f("ix_wikipedia_projects_language_code"), table_name="wikipedia_projects"
    )
    op.drop_index(
        "idx_wikipedia_projects_language_code", table_name="wikipedia_projects"
    )
    op.drop_table("wikipedia_projects")
    # ### end Alembic commands ###
