"""create archived_page_languages link table

Revision ID: 96ffbd77b75c
Revises: 6467179d6d1d
Create Date: 2025-11-21 15:24:57.180689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96ffbd77b75c"
down_revision: Union[str, None] = "6467179d6d1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archived_page_languages",
        sa.Column("archived_page_id", sa.UUID(), nullable=False),
        sa.Column("language_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["archived_page_id"], ["archived_pages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["language_id"], ["wikidata_entities.wikidata_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("archived_page_id", "language_id"),
    )

    # Migrate existing data: link archived pages to languages via Wikipedia project LANGUAGE_OF_WORK relations
    # Match archived page URL to wikipedia_link URL, then get languages from the project
    op.execute("""
        INSERT INTO archived_page_languages (archived_page_id, language_id, created_at, updated_at)
        SELECT DISTINCT ap.id, wr.parent_entity_id, NOW(), NOW()
        FROM archived_pages ap
        INNER JOIN wikipedia_links wl ON ap.url = wl.url
        INNER JOIN wikidata_relations wr ON (
            wr.child_entity_id = wl.wikipedia_project_id
            AND wr.relation_type = 'LANGUAGE_OF_WORK'
        )
        ON CONFLICT DO NOTHING
    """)

    op.drop_index(op.f("ix_archived_pages_iso_639_1"), table_name="archived_pages")
    op.drop_index(op.f("ix_archived_pages_iso_639_2"), table_name="archived_pages")
    op.drop_index(op.f("ix_archived_pages_iso_639_3"), table_name="archived_pages")
    op.drop_index(op.f("ix_archived_pages_wikimedia_code"), table_name="archived_pages")
    op.drop_column("archived_pages", "iso_639_1")
    op.drop_column("archived_pages", "iso_639_2")
    op.drop_column("archived_pages", "wikimedia_code")
    op.drop_column("archived_pages", "iso_639_3")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archived_pages",
        sa.Column("iso_639_3", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "archived_pages",
        sa.Column("wikimedia_code", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "archived_pages",
        sa.Column("iso_639_2", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "archived_pages",
        sa.Column("iso_639_1", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index(
        op.f("ix_archived_pages_wikimedia_code"),
        "archived_pages",
        ["wikimedia_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_archived_pages_iso_639_3"),
        "archived_pages",
        ["iso_639_3"],
        unique=False,
    )
    op.create_index(
        op.f("ix_archived_pages_iso_639_2"),
        "archived_pages",
        ["iso_639_2"],
        unique=False,
    )
    op.create_index(
        op.f("ix_archived_pages_iso_639_1"),
        "archived_pages",
        ["iso_639_1"],
        unique=False,
    )
    op.drop_table("archived_page_languages")
    # ### end Alembic commands ###
