"""add partial index for unevaluated properties

Revision ID: 99eed1071d45
Revises: fcf44927c347
Create Date: 2025-10-12 10:02:14.434595

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99eed1071d45"
down_revision: Union[str, None] = "fcf44927c347"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_properties_unevaluated",
        "properties",
        ["politician_id", "archived_page_id"],
        unique=False,
        postgresql_where=sa.text("statement_id IS NULL AND deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_properties_unevaluated",
        table_name="properties",
        postgresql_where=sa.text("statement_id IS NULL AND deleted_at IS NULL"),
    )
    # ### end Alembic commands ###
