"""add language table

Revision ID: 9b1b145720f8
Revises: 7ea712ad912c
Create Date: 2025-09-24 19:20:31.581788

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b1b145720f8"
down_revision: Union[str, None] = "7ea712ad912c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "languages",
        sa.Column("wikidata_id", sa.String(), nullable=False),
        sa.Column("iso_code", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["wikidata_id"],
            ["wikidata_entities.wikidata_id"],
        ),
        sa.PrimaryKeyConstraint("wikidata_id"),
    )
    op.create_index(
        op.f("ix_languages_iso_code"), "languages", ["iso_code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_languages_iso_code"), table_name="languages")
    op.drop_table("languages")
    # ### end Alembic commands ###
