"""Add CASCADE delete to politician foreign keys

Revision ID: a025b8f896dc
Revises: 0d24f2b5b637
Create Date: 2025-09-18 15:18:38.006476

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a025b8f896dc"
down_revision: Union[str, None] = "0d24f2b5b637"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("born_at_politician_id_fkey"), "born_at", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "born_at", "politicians", ["politician_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("has_citizenship_politician_id_fkey"),
        "has_citizenship",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "has_citizenship",
        "politicians",
        ["politician_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("holds_position_politician_id_fkey"), "holds_position", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "holds_position",
        "politicians",
        ["politician_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("properties_politician_id_fkey"), "properties", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "properties", "politicians", ["politician_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("wikipedia_links_politician_id_fkey"),
        "wikipedia_links",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "wikipedia_links",
        "politicians",
        ["politician_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "wikipedia_links", type_="foreignkey")
    op.create_foreign_key(
        op.f("wikipedia_links_politician_id_fkey"),
        "wikipedia_links",
        "politicians",
        ["politician_id"],
        ["id"],
    )
    op.drop_constraint(None, "properties", type_="foreignkey")
    op.create_foreign_key(
        op.f("properties_politician_id_fkey"),
        "properties",
        "politicians",
        ["politician_id"],
        ["id"],
    )
    op.drop_constraint(None, "holds_position", type_="foreignkey")
    op.create_foreign_key(
        op.f("holds_position_politician_id_fkey"),
        "holds_position",
        "politicians",
        ["politician_id"],
        ["id"],
    )
    op.drop_constraint(None, "has_citizenship", type_="foreignkey")
    op.create_foreign_key(
        op.f("has_citizenship_politician_id_fkey"),
        "has_citizenship",
        "politicians",
        ["politician_id"],
        ["id"],
    )
    op.drop_constraint(None, "born_at", type_="foreignkey")
    op.create_foreign_key(
        op.f("born_at_politician_id_fkey"),
        "born_at",
        "politicians",
        ["politician_id"],
        ["id"],
    )
    # ### end Alembic commands ###
