"""add_campaigns_rename_wikipedia_link_to_source

Revision ID: a90debddd6e1
Revises: 2d84bed67490
Create Date: 2025-12-09 15:17:29.074374

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a90debddd6e1"
down_revision: Union[str, None] = "2d84bed67490"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create new tables first
    op.create_table(
        "campaigns",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("country_id", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["country_id"], ["wikidata_entities.wikidata_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaigns_country_id"), "campaigns", ["country_id"], unique=False
    )

    op.create_table(
        "campaign_positions",
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("position_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["position_id"], ["positions.wikidata_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("campaign_id", "position_id"),
    )
    op.create_index(
        op.f("ix_campaign_positions_position_id"),
        "campaign_positions",
        ["position_id"],
        unique=False,
    )

    op.create_table(
        "campaign_sources",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("politician_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["politician_id"], ["politicians.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaign_sources_campaign_id"),
        "campaign_sources",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_sources_politician_id"),
        "campaign_sources",
        ["politician_id"],
        unique=False,
    )

    op.create_table(
        "wikipedia_sources",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("politician_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("wikipedia_project_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["politician_id"], ["politicians.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["wikipedia_project_id"],
            ["wikipedia_projects.wikidata_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_wikipedia_sources_politician_project",
        "wikipedia_sources",
        ["politician_id", "wikipedia_project_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_wikipedia_sources_wikipedia_project_id"),
        "wikipedia_sources",
        ["wikipedia_project_id"],
        unique=False,
    )

    # 2. Copy data from wikipedia_links to wikipedia_sources
    op.execute("""
        INSERT INTO wikipedia_sources (id, politician_id, url, wikipedia_project_id, created_at, updated_at)
        SELECT id, politician_id, url, wikipedia_project_id, created_at, updated_at
        FROM wikipedia_links
    """)

    # 3. Add new columns to archived_pages
    op.add_column(
        "archived_pages", sa.Column("wikipedia_source_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "archived_pages", sa.Column("campaign_source_id", sa.UUID(), nullable=True)
    )

    # 4. Link archived_pages to wikipedia_sources
    # Match based on wikipedia_project_id - find the wikipedia_source for the same project
    # that belongs to a politician whose properties are linked to this archived_page
    op.execute("""
        UPDATE archived_pages ap
        SET wikipedia_source_id = ws.id
        FROM wikipedia_sources ws
        WHERE ap.wikipedia_project_id = ws.wikipedia_project_id
        AND ap.wikipedia_project_id IS NOT NULL
        AND EXISTS (
            SELECT 1 FROM properties p
            WHERE p.archived_page_id = ap.id
            AND p.politician_id = ws.politician_id
        )
    """)

    # 5. Create indexes and foreign keys for archived_pages
    op.drop_index(
        op.f("ix_archived_pages_wikipedia_project_id"), table_name="archived_pages"
    )
    op.create_index(
        op.f("ix_archived_pages_campaign_source_id"),
        "archived_pages",
        ["campaign_source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_archived_pages_wikipedia_source_id"),
        "archived_pages",
        ["wikipedia_source_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("archived_pages_wikipedia_project_id_fkey"),
        "archived_pages",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "archived_pages",
        "wikipedia_sources",
        ["wikipedia_source_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "archived_pages",
        "campaign_sources",
        ["campaign_source_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # 6. Drop old columns from archived_pages
    op.drop_column("archived_pages", "wikipedia_project_id")
    op.drop_column("archived_pages", "permanent_url")

    # 7. Drop old trigger for wikipedia_links before dropping the table
    op.execute(
        "DROP TRIGGER IF EXISTS trigger_update_wikipedia_links_updated_at ON wikipedia_links;"
    )

    # 8. Drop the old wikipedia_links table
    op.drop_index(
        op.f("idx_wikipedia_links_politician_project"), table_name="wikipedia_links"
    )
    op.drop_index(
        op.f("ix_wikipedia_links_wikipedia_project_id"), table_name="wikipedia_links"
    )
    op.drop_table("wikipedia_links")

    # 9. Add CHECK constraint for exactly one source FK
    op.create_check_constraint(
        "check_exactly_one_source",
        "archived_pages",
        "(wikipedia_source_id IS NOT NULL AND campaign_source_id IS NULL) OR "
        "(wikipedia_source_id IS NULL AND campaign_source_id IS NOT NULL)",
    )

    # 10. Create updated_at triggers for new tables
    op.execute("""
        CREATE OR REPLACE TRIGGER trigger_update_wikipedia_sources_updated_at
        BEFORE UPDATE ON wikipedia_sources
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at_column();
    """)
    op.execute("""
        CREATE OR REPLACE TRIGGER trigger_update_campaigns_updated_at
        BEFORE UPDATE ON campaigns
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at_column();
    """)
    op.execute("""
        CREATE OR REPLACE TRIGGER trigger_update_campaign_sources_updated_at
        BEFORE UPDATE ON campaign_sources
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at_column();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop CHECK constraint first
    op.drop_constraint("check_exactly_one_source", "archived_pages", type_="check")

    op.add_column(
        "archived_pages",
        sa.Column("permanent_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "archived_pages",
        sa.Column(
            "wikipedia_project_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "archived_pages", type_="foreignkey")
    op.drop_constraint(None, "archived_pages", type_="foreignkey")
    op.create_foreign_key(
        op.f("archived_pages_wikipedia_project_id_fkey"),
        "archived_pages",
        "wikipedia_projects",
        ["wikipedia_project_id"],
        ["wikidata_id"],
        ondelete="SET NULL",
    )
    op.drop_index(
        op.f("ix_archived_pages_wikipedia_source_id"), table_name="archived_pages"
    )
    op.drop_index(
        op.f("ix_archived_pages_campaign_source_id"), table_name="archived_pages"
    )
    op.create_index(
        op.f("ix_archived_pages_wikipedia_project_id"),
        "archived_pages",
        ["wikipedia_project_id"],
        unique=False,
    )
    op.drop_column("archived_pages", "campaign_source_id")
    op.drop_column("archived_pages", "wikipedia_source_id")
    op.create_table(
        "wikipedia_links",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("politician_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "wikipedia_project_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["politician_id"],
            ["politicians.id"],
            name=op.f("wikipedia_links_politician_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["wikipedia_project_id"],
            ["wikipedia_projects.wikidata_id"],
            name=op.f("wikipedia_links_wikipedia_project_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("wikipedia_links_pkey")),
    )
    op.create_index(
        op.f("ix_wikipedia_links_wikipedia_project_id"),
        "wikipedia_links",
        ["wikipedia_project_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_wikipedia_links_politician_project"),
        "wikipedia_links",
        ["politician_id", "wikipedia_project_id"],
        unique=True,
    )
    op.drop_index(
        op.f("ix_wikipedia_sources_wikipedia_project_id"),
        table_name="wikipedia_sources",
    )
    op.drop_index(
        "idx_wikipedia_sources_politician_project", table_name="wikipedia_sources"
    )
    op.drop_table("wikipedia_sources")
    op.drop_index(
        op.f("ix_campaign_sources_politician_id"), table_name="campaign_sources"
    )
    op.drop_index(
        op.f("ix_campaign_sources_campaign_id"), table_name="campaign_sources"
    )
    op.drop_table("campaign_sources")
    op.drop_index(
        op.f("ix_campaign_positions_position_id"), table_name="campaign_positions"
    )
    op.drop_table("campaign_positions")
    op.drop_index(op.f("ix_campaigns_country_id"), table_name="campaigns")
    op.drop_table("campaigns")
    # ### end Alembic commands ###
