"""Add enriched_at timestamp to politicians

Revision ID: aa07180f92ea
Revises: 6df466099161
Create Date: 2025-09-03 16:10:55.565602

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa07180f92ea"
down_revision: Union[str, None] = "6df466099161"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("politicians", sa.Column("enriched_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("politicians", "enriched_at")
    # ### end Alembic commands ###
