"""Add statement_id fields to Property, HoldsPosition, and BornAt

Revision ID: ae31edcb469c
Revises: ed4363cb43f2
Create Date: 2025-09-18 11:11:17.676931

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae31edcb469c"
down_revision: str | None = "ed4363cb43f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("born_at", sa.Column("statement_id", sa.String(), nullable=True))
    op.add_column(
        "holds_position", sa.Column("statement_id", sa.String(), nullable=True)
    )
    op.add_column("properties", sa.Column("statement_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("properties", "statement_id")
    op.drop_column("holds_position", "statement_id")
    op.drop_column("born_at", "statement_id")
    # ### end Alembic commands ###
