"""add_embedding_column_to_positions

Revision ID: b140cc2468c3
Revises: 544ff8941985
Create Date: 2025-06-17 16:34:29.802483

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b140cc2468c3"
down_revision: Union[str, None] = "544ff8941985"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL with pgvector
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("ALTER TABLE positions ADD COLUMN embedding vector(384)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("positions", "embedding")
    # ### end Alembic commands ###
