"""allow multiple time periods for same position

Revision ID: b9c3f7644b36
Revises: e6cee728924e
Create Date: 2025-08-29 16:14:34.171156

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9c3f7644b36"
down_revision: str | None = "e6cee728924e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uq_holds_position_wikidata_only"),
        table_name="holds_position",
        postgresql_where="(archived_page_id IS NULL)",
    )
    op.create_index(
        "uq_holds_position_wikidata_only",
        "holds_position",
        ["politician_id", "position_id", "start_date", "end_date"],
        unique=True,
        postgresql_where=sa.text("archived_page_id IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_holds_position_wikidata_only",
        table_name="holds_position",
        postgresql_where=sa.text("archived_page_id IS NULL"),
    )
    op.create_index(
        op.f("uq_holds_position_wikidata_only"),
        "holds_position",
        ["politician_id", "position_id"],
        unique=True,
        postgresql_where="(archived_page_id IS NULL)",
    )
    # ### end Alembic commands ###
