"""Add WikidataDump model for tracking dump processing

Revision ID: bb1c034b9515
Revises: b9c3f7644b36
Create Date: 2025-09-02 17:20:55.122822

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb1c034b9515"
down_revision: str | None = "b9c3f7644b36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wikidata_dumps",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("last_modified", sa.DateTime(), nullable=False),
        sa.Column("downloaded_at", sa.DateTime(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(), nullable=True),
        sa.Column("imported_hierarchy_at", sa.DateTime(), nullable=True),
        sa.Column("imported_entities_at", sa.DateTime(), nullable=True),
        sa.Column("imported_politicians_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikidata_dumps")
    # ### end Alembic commands ###
