"""Add unique indexes on statement_id fields

Revision ID: c120ebe24dd2
Revises: ae31edcb469c
Create Date: 2025-09-18 12:09:20.193985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c120ebe24dd2"
down_revision: Union[str, None] = "ae31edcb469c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_born_at_statement_id",
        "born_at",
        ["statement_id"],
        unique=True,
        postgresql_where=sa.text("statement_id IS NOT NULL"),
    )
    op.create_index(
        "uq_holds_position_statement_id",
        "holds_position",
        ["statement_id"],
        unique=True,
        postgresql_where=sa.text("statement_id IS NOT NULL"),
    )
    op.create_index(
        "uq_properties_statement_id",
        "properties",
        ["statement_id"],
        unique=True,
        postgresql_where=sa.text("statement_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_properties_statement_id",
        table_name="properties",
        postgresql_where=sa.text("statement_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_holds_position_statement_id",
        table_name="holds_position",
        postgresql_where=sa.text("statement_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_born_at_statement_id",
        table_name="born_at",
        postgresql_where=sa.text("statement_id IS NOT NULL"),
    )
    # ### end Alembic commands ###
