"""drop origin from archived_pages

Revision ID: c672027b4236
Revises: dc95c6eff4bf
Create Date: 2026-03-17 14:25:13.879872

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c672027b4236"
down_revision: Union[str, None] = "dc95c6eff4bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("archived_pages", "origin")
    sa.Enum(name="archivedpageorigin").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archived_pages",
        sa.Column(
            "origin",
            postgresql.ENUM("ENRICHMENT", "USER_SUBMITTED", name="archivedpageorigin"),
            server_default=sa.text("'ENRICHMENT'::archivedpageorigin"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
