"""add embedding column to country model

Revision ID: ca1f55abed5b
Revises: e7369f077a07
Create Date: 2025-09-25 12:39:59.628768

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = "ca1f55abed5b"
down_revision: Union[str, None] = "e7369f077a07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("countries", sa.Column("embedding", Vector(384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("countries", "embedding")
    # ### end Alembic commands ###
