"""add_revision_column_to_archived_pages

Revision ID: cadc912d1eba
Revises: f6cade58c75c
Create Date: 2025-11-24 13:36:21.712801

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cadc912d1eba"
down_revision: Union[str, None] = "f6cade58c75c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("archived_pages", sa.Column("revision", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("archived_pages", "revision")
    # ### end Alembic commands ###
