"""add permanent_url to archived_pages

Revision ID: cba9fff2bbbe
Revises: 741004a3d33e
Create Date: 2025-11-25 09:35:14.811445

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cba9fff2bbbe"
down_revision: str | None = "741004a3d33e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archived_pages", sa.Column("permanent_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("archived_pages", "permanent_url")
    # ### end Alembic commands ###
