"""Add wikidata_id_numeric to politicians

Revision ID: cbbf26f62a09
Revises: 644e26e83904
Create Date: 2025-10-07 16:29:00.113365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cbbf26f62a09"
down_revision: Union[str, None] = "644e26e83904"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "politicians", sa.Column("wikidata_id_numeric", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_politicians_wikidata_id_numeric"),
        "politicians",
        ["wikidata_id_numeric"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Populate wikidata_id_numeric from wikidata_id (strip 'Q' prefix and convert to integer)
    op.execute("""
        UPDATE politicians
        SET wikidata_id_numeric = CAST(SUBSTRING(wikidata_id FROM 2) AS INTEGER)
        WHERE wikidata_id IS NOT NULL AND wikidata_id LIKE 'Q%'
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_politicians_wikidata_id_numeric"), table_name="politicians")
    op.drop_column("politicians", "wikidata_id_numeric")
    # ### end Alembic commands ###
