"""Add Country model and update Position to reference countries

Revision ID: cd9dab1bc0ad
Revises: f4558f9f13a2
Create Date: 2025-06-12 11:16:40.972209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd9dab1bc0ad'
down_revision: Union[str, None] = 'f4558f9f13a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('iso_code', sa.String(), nullable=True),
    sa.Column('wikidata_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_iso_code'), 'countries', ['iso_code'], unique=True)
    op.create_index(op.f('ix_countries_wikidata_id'), 'countries', ['wikidata_id'], unique=True)
    op.add_column('positions', sa.Column('country_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'positions', 'countries', ['country_id'], ['id'])
    op.drop_column('positions', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('country', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_column('positions', 'country_id')
    op.drop_index(op.f('ix_countries_wikidata_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_iso_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
