"""Add soft delete columns

Revision ID: ce8ea667765a
Revises: 53a44de8d7ff
Create Date: 2025-09-25 16:14:37.368345

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ce8ea667765a"
down_revision: Union[str, None] = "53a44de8d7ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("properties", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column(
        "wikidata_entities", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "wikidata_relations", sa.Column("deleted_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wikidata_relations", "deleted_at")
    op.drop_column("wikidata_entities", "deleted_at")
    op.drop_column("properties", "deleted_at")
    # ### end Alembic commands ###
