"""add labels array field to locations

Revision ID: cfdbf2ed21ed
Revises: 2ed06e26f119
Create Date: 2025-10-08 21:33:32.619680

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfdbf2ed21ed"
down_revision: str | None = "2ed06e26f119"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("locations", sa.Column("labels", sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "labels")
    # ### end Alembic commands ###
