"""add labels array field to locations

Revision ID: cfdbf2ed21ed
Revises: 2ed06e26f119
Create Date: 2025-10-08 21:33:32.619680

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cfdbf2ed21ed"
down_revision: Union[str, None] = "2ed06e26f119"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("locations", sa.Column("labels", sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "labels")
    # ### end Alembic commands ###
