"""drop_trigram_index

Revision ID: d6772e534c56
Revises: 362f0d0d7ac8
Create Date: 2025-12-13 12:51:25.339213

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d6772e534c56"
down_revision: Union[str, None] = "362f0d0d7ac8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_wikidata_entity_labels_label_gin"),
        table_name="wikidata_entity_labels",
        postgresql_ops={"label": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_wikidata_entity_labels_label_gin"),
        "wikidata_entity_labels",
        ["label"],
        unique=False,
        postgresql_ops={"label": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
