"""add politician_id to archived_pages

Revision ID: da4eb3c240eb
Revises: 8dcb99038884
Create Date: 2026-03-12 13:24:21.293273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da4eb3c240eb"
down_revision: Union[str, None] = "8dcb99038884"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archived_pages", sa.Column("politician_id", sa.UUID(), nullable=True)
    )
    op.create_index(
        op.f("ix_archived_pages_politician_id"),
        "archived_pages",
        ["politician_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "archived_pages",
        "politicians",
        ["politician_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "archived_pages", type_="foreignkey")
    op.drop_index(op.f("ix_archived_pages_politician_id"), table_name="archived_pages")
    op.drop_column("archived_pages", "politician_id")
    # ### end Alembic commands ###
