"""drop user_filter_preferences

Revision ID: dbf83ff1fb9d
Revises: 45df26b10a72
Create Date: 2026-04-30 17:40:15.539230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dbf83ff1fb9d"
down_revision: Union[str, None] = "45df26b10a72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_filter_user"), table_name="user_filter_preferences")
    op.drop_table("user_filter_preferences")
    op.execute("DROP TYPE IF EXISTS preferencetype")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_filter_preferences",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "preference_type",
            postgresql.ENUM("LANGUAGE", "COUNTRY", name="preferencetype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("entity_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["wikidata_entities.wikidata_id"],
            name=op.f("user_filter_preferences_entity_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_filter_preferences_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "preference_type",
            "entity_id",
            name=op.f("uq_user_filter_user_type_entity"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_user_filter_user"),
        "user_filter_preferences",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###
