"""add origin to archived_pages

Revision ID: dc95c6eff4bf
Revises: 377c9f78ae09
Create Date: 2026-03-13 20:53:47.733019

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc95c6eff4bf"
down_revision: Union[str, None] = "377c9f78ae09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    archivedpageorigin = sa.Enum(
        "ENRICHMENT", "USER_SUBMITTED", name="archivedpageorigin"
    )
    archivedpageorigin.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "archived_pages",
        sa.Column(
            "origin", archivedpageorigin, server_default="ENRICHMENT", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("archived_pages", "origin")
    sa.Enum(name="archivedpageorigin").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
