"""Drop name columns from positions and locations tables

Revision ID: dd9ba46e21cd
Revises: a4ffd33b8abc
Create Date: 2025-09-09 20:27:47.748806

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd9ba46e21cd"
down_revision: Union[str, None] = "a4ffd33b8abc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("locations", "name")
    op.drop_column("positions", "name")
    op.drop_index(
        op.f("ix_wikidata_relations_child_entity_id"), table_name="wikidata_relations"
    )
    op.drop_index(
        op.f("ix_wikidata_relations_parent_entity_id"), table_name="wikidata_relations"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_wikidata_relations_parent_entity_id"),
        "wikidata_relations",
        ["parent_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wikidata_relations_child_entity_id"),
        "wikidata_relations",
        ["child_entity_id"],
        unique=False,
    )
    op.add_column(
        "positions",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "locations",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
