"""Add user preference system with PreferenceType enum and Preference model

Revision ID: e7369f077a07
Revises: 8a2b32cf5d4a
Create Date: 2025-09-24 21:30:53.587213

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7369f077a07"
down_revision: Union[str, None] = "8a2b32cf5d4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preferences",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "preference_type",
            sa.Enum("LANGUAGE", "COUNTRY", name="preferencetype"),
            nullable=False,
        ),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["wikidata_entities.wikidata_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_preferences_user_type_entity",
        "preferences",
        ["user_id", "preference_type", "entity_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_preferences_user_type_entity", table_name="preferences")
    op.drop_table("preferences")
    # ### end Alembic commands ###
