"""add language iso_code indexes and column updates

Revision ID: ee5fe228aa1c
Revises: 9b1b145720f8
Create Date: 2025-09-24 19:54:21.882490

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee5fe228aa1c"
down_revision: Union[str, None] = "9b1b145720f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("archived_pages", sa.Column("iso_code", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_archived_pages_iso_code"), "archived_pages", ["iso_code"], unique=False
    )

    # Rename language_code column to iso_code in wikipedia_links
    op.alter_column("wikipedia_links", "language_code", new_column_name="iso_code")

    # Update indexes to use new column name
    op.drop_index(
        op.f("idx_wikipedia_links_politician_language"), table_name="wikipedia_links"
    )
    op.create_index(
        "idx_wikipedia_links_politician_iso_code",
        "wikipedia_links",
        ["politician_id", "iso_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_wikipedia_links_iso_code"),
        "wikipedia_links",
        ["iso_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert wikipedia_links column and index changes
    op.drop_index(op.f("ix_wikipedia_links_iso_code"), table_name="wikipedia_links")
    op.drop_index(
        "idx_wikipedia_links_politician_iso_code", table_name="wikipedia_links"
    )

    # Rename iso_code back to language_code
    op.alter_column("wikipedia_links", "iso_code", new_column_name="language_code")

    # Recreate original index
    op.create_index(
        op.f("idx_wikipedia_links_politician_language"),
        "wikipedia_links",
        ["politician_id", "language_code"],
        unique=True,
    )

    # Remove archived_pages changes
    op.drop_index(op.f("ix_archived_pages_iso_code"), table_name="archived_pages")
    op.drop_column("archived_pages", "iso_code")
    # ### end Alembic commands ###
