"""Add Language and OfficialLanguage models

Revision ID: efac383f80e8
Revises: 3b5cfba705c9
Create Date: 2025-09-17 14:19:16.813153

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "efac383f80e8"
down_revision: Union[str, None] = "3b5cfba705c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "languages",
        sa.Column("wikidata_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["wikidata_id"],
            ["wikidata_entities.wikidata_id"],
        ),
        sa.PrimaryKeyConstraint("wikidata_id"),
    )
    op.create_table(
        "official_languages",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("country_id", sa.String(), nullable=False),
        sa.Column("language_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.wikidata_id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.wikidata_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("country_id", "language_id", name="uq_country_language"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("official_languages")
    op.drop_table("languages")
    # ### end Alembic commands ###
