"""allow null values in wikidata_classes name column

Revision ID: efc8c4f590c7
Revises: 9973a8323817
Create Date: 2025-08-22 14:48:45.470054

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "efc8c4f590c7"
down_revision: Union[str, None] = "9973a8323817"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "wikidata_classes", "name", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "wikidata_classes", "name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
