"""remove_country_column_from_politician

Revision ID: f4558f9f13a2
Revises: 54299cab93c2
Create Date: 2025-06-11 19:32:29.410615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4558f9f13a2'
down_revision: Union[str, None] = '54299cab93c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('politicians', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('politicians', sa.Column('country', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
