"""add gin index on wikidata_entities labels for pg_trgm

Revision ID: f59dee05bf16
Revises: d76707579b83
Create Date: 2025-10-09 11:00:35.075364

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f59dee05bf16"
down_revision: Union[str, None] = "d76707579b83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_wikidata_entities_labels_gin",
        "wikidata_entities",
        ["labels"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"labels": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_wikidata_entities_labels_gin",
        table_name="wikidata_entities",
        postgresql_using="gin",
        postgresql_ops={"labels": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
