"""add performance indexes for politicians route

Revision ID: f6cade58c75c
Revises: 6528df629848
Create Date: 2025-11-23 15:32:44.541028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6cade58c75c"
down_revision: Union[str, None] = "6528df629848"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_archived_page_languages_language_id"),
        "archived_page_languages",
        ["language_id"],
        unique=False,
    )
    op.create_index(
        "idx_properties_citizenship_lookup",
        "properties",
        ["politician_id", "type", "entity_id"],
        unique=False,
        postgresql_where=sa.text("type = 'CITIZENSHIP' AND deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_properties_citizenship_lookup",
        table_name="properties",
        postgresql_where=sa.text("type = 'CITIZENSHIP' AND deleted_at IS NULL"),
    )
    op.drop_index(
        op.f("ix_archived_page_languages_language_id"),
        table_name="archived_page_languages",
    )
    # ### end Alembic commands ###
