"""Remove language_id from wikipedia_projects, use wikidata_relations for P407

Revision ID: f790105d9d6d
Revises: 936f6249b794
Create Date: 2025-11-16 16:34:15.541657

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f790105d9d6d"
down_revision: Union[str, None] = "936f6249b794"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new P407 (LANGUAGE_OF_WORK) value to relationtype enum
    op.execute("ALTER TYPE relationtype ADD VALUE IF NOT EXISTS 'LANGUAGE_OF_WORK'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("wikipedia_projects_language_id_fkey"),
        "wikipedia_projects",
        type_="foreignkey",
    )
    op.drop_column("wikipedia_projects", "language_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wikipedia_projects",
        sa.Column("language_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("wikipedia_projects_language_id_fkey"),
        "wikipedia_projects",
        "languages",
        ["language_id"],
        ["wikidata_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
