"""add index on child_entity_id

Revision ID: fcf44927c347
Revises: ed77bf57de13
Create Date: 2025-10-11 13:09:46.964312

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fcf44927c347"
down_revision: Union[str, None] = "ed77bf57de13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_wikidata_relations_child_entity_id"),
        "wikidata_relations",
        ["child_entity_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_wikidata_relations_child_entity_id"), table_name="wikidata_relations"
    )
    # ### end Alembic commands ###
